# -*- coding: utf-8 -*-
__all__ = ['ASKER_QUESTION_QUEUE', 'BRAINER_QUESTION_QUEUE',
           'BRAINER_QUESTION_QUEUE_QUESTION_KEY', 'BRAINER_QUESTION_QUEUE_ANSWER_KEY']

ASKER_QUESTION_QUEUE = 'asker_question_queue'
BRAINER_QUESTION_QUEUE = 'brainer_question_queue'
BRAINER_QUESTION_QUEUE_QUESTION_KEY = 'question'
BRAINER_QUESTION_QUEUE_ANSWER_KEY = 'answer'

